apiVersion: v1
kind: Namespace
metadata:
  name: fabio-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabio-api
  namespace: fullstack-app
spec:
  selector:
    matchLabels:
      app: fabio-api
  replicas: 1
  template:
    metadata:
      labels:
        app: fabio-api
    spec:
      containers:
        - name: fabio-api
          image: fabioi82/hello-api:latest
          env:
            - name: DB_HOST
              value: "mysql.fullstack-app.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "meinPasswort"
            - name: DB_NAME
              value: "testdb"
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fabio-api-ingress
  namespace: fullstack-app # phpmyadmin-app
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: fabio-api.app.topadata.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fabioapi
                port:
                  number: 5678
  tls:
    - secretName: fabioapi-tls
      hosts:
        - fabio-api.app.topadata.ch
---
apiVersion: v1
kind: Service
metadata: 
  name: fabio-api-service
  namespace: fullstack-app
spec:
  type: ClusterIP
  selector:  # Korrektur hier
    app: fabio-api
  ports:  # Korrektur hier
    - protocol: TCP
      port: 5678
      targetPort: 3000
