apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql"
        - name: PMA_USER
          value: "user"
        - name: PMA_PASSWORD
          value: "password"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: phpmyadmin
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: phpmyadmin.app.topadata.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 3000
  tls:
    - secretName: phpmyadmin-tls
      hosts:
        - phpmyadmin.app.topadata.ch
