apiVersion: v1
kind: Namespace
metadata:
  name: fullstack-app  # Namespace für MySQL und API
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fullstack-app
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:  # <--- Hier wird das Secret hinzugefügt
        - name: my-docker-secret
      containers:
        - name: mysql
          image: mysql:8
          args:
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "meinPasswort"
            - name: MYSQL_DATABASE
              value: "testdb"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fullstack-app
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: my-api
          image: fransafu/simple-rest-golang:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql.fullstack-app.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "meinPasswort"
            - name: DB_NAME
              value: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: my-api
  namespace: fullstack-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: my-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-ingress
  namespace: fullstack-app
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: api.app.topadata.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-api
                port:
                  number: 3000
  tls:
    - secretName: fullstack-tls
      hosts:
        - api.app.topadata.ch
